runner:
  revive:
    cmd: revive -config .revive.toml $(go list ./...)
    errorformat:
      - "%f:%l:%c: %m"
  govet:
    cmd: go vet $(go list ./...)
  # megacheck == (staticcheck + gosimple + unused)
  megacheck:
    cmd: megacheck $(go list ./...)
    errorformat:
      - "%f:%l:%c: %m"
  errcheck:
    cmd: errcheck -asserts -ignoretests -blank $(go list ./...)
    errorformat:
      - "%f:%l:%c:%m"